package hust.libgdx.tool.views.renderers.properties;

public enum ActorPropertyType {
	NAME, X, Y, WIDTH, HEIGHT, DEBUG, VISIBLE,
	TEXT, ALIGN, WRAP, FONT_SCALE_X, FONT_SCALE_Y, ELLIPSIS,
	PAD_LEFT, PAD_RIGHT, PAD_TOP, PAD_BOTTOM, CHECK, DISABLE,
	MIN, MAX, STEP, INIT,
	SCALING, IMAGE,
	ROTATION, COLOR, FLIP_X, FLIP_Y, SCALE_X, SCALE_Y
}
